// Generated by scripts/generate-quiz1-audio.py. Do not edit manually.
export const QUIZ1_AUDIO_METADATA = Object.freeze({
  "model": "gemini-3.1-flash-tts-preview",
  "voice": "Kore",
  "promptVersion": "warm-japanese-exact-v1",
  "sampleRate": 24000,
  "count": 1
});

export const QUIZ1_AUDIO_MANIFEST = Object.freeze({
  "beginner-part1-quiz1-q1": {
    "path": "/audio/quiz1/1273f84c39ceddf34620.wav",
    "text": "くいずたいむ！「がらすが ひつよう」は えいごで？",
    "source": "beginner:part1.quiz1.q1"
  }
});
