// Generated by scripts/generate-ending-audio.py. Do not edit manually.
export const ENDING_AUDIO_METADATA = Object.freeze({
  "model": "gemini-3.1-flash-tts-preview",
  "voice": "Kore",
  "promptVersion": "warm-bilingual-exact-v1",
  "sampleRate": 24000,
  "count": 2
});

export const ENDING_AUDIO_MANIFEST = Object.freeze({
  "beginner-part1-turn-a": {
    "path": "/audio/ending/a7772de8515131bc8d16.wav",
    "text": "Perfect! We made a fish tank together! Thank you for helping! ぱーふぇくと！ いっしょに すいそうを つくれたね！ てつだって くれて ありがとう！ Hold on... we don't have any fish in the fish tank! That's for next time! あれれ… おさかなが 1ぴきも いない！ それは つぎの レッスンだね！ What kind of fish should we catch? どんな おさかなを つかまえよう？",
    "source": "beginner:part1.ending1.turnA"
  },
  "beginner-part1-turn-c": {
    "path": "/audio/ending/7932bb0544e598b2ac90.wav",
    "text": "Hmm... I can't stop thinking about it! うーん… わくわく しちゃう！ Next Minecraft lesson we'll decorate this tank and add fish to finish it! See you next time! つぎの まいんくらふと レッスンで この すいそうを かざって おさかなを いれて かんせい させよう！ また ね！",
    "source": "beginner:part1.ending1.turnC"
  }
});
