// Generated by scripts/generate-ch4-audio.py. Do not edit manually.
export const CH4_AUDIO_METADATA = Object.freeze({
  "model": "gemini-3.1-flash-tts-preview",
  "voice": "Kore",
  "promptVersion": "warm-bilingual-exact-v1",
  "sampleRate": 24000,
  "count": 6
});

export const CH4_AUDIO_MANIFEST = Object.freeze({
  "beginner-part1-ch4-make-tell-blue": {
    "path": "/audio/ch4/e40c84981cc0ce2540c0.wav",
    "text": "Let's make blue coloured glass! Tell me when you make one! あおいろの がらすを つくろう！つくれたら「あおいろの がらすを つくった！」って えいごで おしえてね！",
    "color": "blue",
    "source": "beginner:part1.ch4.makeTell.blue"
  },
  "beginner-part1-ch4-make-tell-green": {
    "path": "/audio/ch4/05a2638a219c838adf11.wav",
    "text": "Let's make green coloured glass! Tell me when you make one! みどりいろの がらすを つくろう！つくれたら「みどりいろの がらすを つくった！」って えいごで おしえてね！",
    "color": "green",
    "source": "beginner:part1.ch4.makeTell.green"
  },
  "beginner-part1-ch4-make-tell-orange": {
    "path": "/audio/ch4/ebd8232a7a7659c85bbf.wav",
    "text": "Let's make orange coloured glass! Tell me when you make one! おれんじいろの がらすを つくろう！つくれたら「おれんじいろの がらすを つくった！」って えいごで おしえてね！",
    "color": "orange",
    "source": "beginner:part1.ch4.makeTell.orange"
  },
  "beginner-part1-ch4-make-tell-pink": {
    "path": "/audio/ch4/68904f651cd7102d9019.wav",
    "text": "Let's make pink coloured glass! Tell me when you make one! ぴんくいろの がらすを つくろう！つくれたら「ぴんくいろの がらすを つくった！」って えいごで おしえてね！",
    "color": "pink",
    "source": "beginner:part1.ch4.makeTell.pink"
  },
  "beginner-part1-ch4-make-tell-red": {
    "path": "/audio/ch4/47f53bbb84fdf7993fb7.wav",
    "text": "Let's make red coloured glass! Tell me when you make one! あかいろの がらすを つくろう！つくれたら「あかいろの がらすを つくった！」って えいごで おしえてね！",
    "color": "red",
    "source": "beginner:part1.ch4.makeTell.red"
  },
  "beginner-part1-ch4-make-tell-yellow": {
    "path": "/audio/ch4/fc7c9f81e4dc6184766b.wav",
    "text": "Let's make yellow coloured glass! Tell me when you make one! きいろいろの がらすを つくろう！つくれたら「きいろいろの がらすを つくった！」って えいごで おしえてね！",
    "color": "yellow",
    "source": "beginner:part1.ch4.makeTell.yellow"
  }
});
