// Generated by scripts/generate-mcq-audio.py. Do not edit manually.
export const MCQ_AUDIO_METADATA = Object.freeze({
  "model": "gemini-3.1-flash-tts-preview",
  "voice": "Kore",
  "promptVersion": "warm-clear-exact-v1",
  "sampleRate": 24000,
  "count": 53
});

export const MCQ_AUDIO_MANIFEST = Object.freeze({
  "back": {
    "path": "/audio/mcq/dc16aaefe0bbbf432e5c.wav",
    "text": "back",
    "spokenText": "back",
    "source": "beginner:part1.segments[2].mcqBeats[1].choices[3]"
  },
  "beach": {
    "path": "/audio/mcq/b9c7a11ae474b8ee209e.wav",
    "text": "beach",
    "spokenText": "beach",
    "source": "beginner:part1.segments[2].mcqBeats[0].choices[0]"
  },
  "dirt": {
    "path": "/audio/mcq/6f0c5a91793cd1bf4382.wav",
    "text": "dirt",
    "spokenText": "dirt",
    "source": "beginner:part1.segments[1].mcqBeats[0].choices[3]"
  },
  "forest": {
    "path": "/audio/mcq/6ae71639d0b26759258f.wav",
    "text": "forest",
    "spokenText": "forest",
    "source": "beginner:part1.segments[2].mcqBeats[0].choices[3]"
  },
  "glass": {
    "path": "/audio/mcq/4d0ae57fd025b054c30b.wav",
    "text": "glass",
    "spokenText": "glass",
    "source": "beginner:part1.segments[1].mcqBeats[0].choices[0]"
  },
  "i choose blue": {
    "path": "/audio/mcq/e87b21e51944efef4cd9.wav",
    "text": "I choose blue",
    "spokenText": "I choose blue.",
    "source": "beginner:part1.segments[9].items[8].choices[2]"
  },
  "i found glass": {
    "path": "/audio/mcq/ba259ac30e56ec45a111.wav",
    "text": "I found glass",
    "spokenText": "I found glass.",
    "source": "beginner:part1.segments[1].mcqBeats[1].choices[1]"
  },
  "i found sand": {
    "path": "/audio/mcq/9be69ecee79e6678a471.wav",
    "text": "I found sand",
    "spokenText": "I found sand.",
    "source": "beginner:part1.segments[1].mcqBeats[3].choices[1]"
  },
  "i found some sand!": {
    "path": "/audio/mcq/87205bcb2bb97f6ff86e.wav",
    "text": "I found some sand!",
    "spokenText": "I found some sand!",
    "source": "beginner:part1.segments[2].mcqBeats[2].choices[0]"
  },
  "i made a tank!": {
    "path": "/audio/mcq/d76a005f7faebe779a3c.wav",
    "text": "I made a tank!",
    "spokenText": "I made a tank!",
    "source": "beginner:part1.segments[3].mcqBeats[1].choices[3]"
  },
  "i made black glass!": {
    "path": "/audio/mcq/eb7d2bc31a33f71ff245.wav",
    "text": "I made black glass!",
    "spokenText": "I made black glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i made blue glass!": {
    "path": "/audio/mcq/bf4b70911ef960732f96.wav",
    "text": "I made blue glass!",
    "spokenText": "I made blue glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i made brown glass!": {
    "path": "/audio/mcq/678067ff44ca5d8ec654.wav",
    "text": "I made brown glass!",
    "spokenText": "I made brown glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i made cyan glass!": {
    "path": "/audio/mcq/b0248c776acc8632262a.wav",
    "text": "I made cyan glass!",
    "spokenText": "I made cyan glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i made glass": {
    "path": "/audio/mcq/642622d07d8c329ffd97.wav",
    "text": "I made glass",
    "spokenText": "I made glass.",
    "source": "beginner:part1.segments[1].mcqBeats[3].choices[3]"
  },
  "i made glass!": {
    "path": "/audio/mcq/8d285cc6a384b0847178.wav",
    "text": "I made glass!",
    "spokenText": "I made glass!",
    "source": "beginner:part1.segments[2].mcqBeats[2].choices[2]"
  },
  "i made green glass!": {
    "path": "/audio/mcq/46c2b40994b04fa2dff2.wav",
    "text": "I made green glass!",
    "spokenText": "I made green glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i made lime glass!": {
    "path": "/audio/mcq/6df5d611bf128c9c923b.wav",
    "text": "I made lime glass!",
    "spokenText": "I made lime glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i made magenta glass!": {
    "path": "/audio/mcq/61937145e0c5def7f2d5.wav",
    "text": "I made magenta glass!",
    "spokenText": "I made magenta glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i made orange glass!": {
    "path": "/audio/mcq/a89ac5b022b3b33ebb59.wav",
    "text": "I made orange glass!",
    "spokenText": "I made orange glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i made pink glass!": {
    "path": "/audio/mcq/1ce42aa45cbbcef71b51.wav",
    "text": "I made pink glass!",
    "spokenText": "I made pink glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i made purple glass!": {
    "path": "/audio/mcq/b684ae768cb96f5939b4.wav",
    "text": "I made purple glass!",
    "spokenText": "I made purple glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i made red glass": {
    "path": "/audio/mcq/1bfe5d5a0384bffcef05.wav",
    "text": "I made red glass",
    "spokenText": "I made red glass.",
    "source": "beginner:part1.segments[9].items[9].choices[0]"
  },
  "i made red glass!": {
    "path": "/audio/mcq/1f4edefc2bfa3170b415.wav",
    "text": "I made red glass!",
    "spokenText": "I made red glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i made sand": {
    "path": "/audio/mcq/716211cfa204b9aad8e5.wav",
    "text": "I made sand",
    "spokenText": "I made sand.",
    "source": "beginner:part1.segments[1].mcqBeats[1].choices[2]"
  },
  "i made white glass!": {
    "path": "/audio/mcq/05a7ca612415048df1c2.wav",
    "text": "I made white glass!",
    "spokenText": "I made white glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i made yellow glass!": {
    "path": "/audio/mcq/383e28f6733dcfc5aab4.wav",
    "text": "I made yellow glass!",
    "spokenText": "I made yellow glass!",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[0]"
  },
  "i need a dye": {
    "path": "/audio/mcq/991fc4d4e0a92f0c5c25.wav",
    "text": "I need a dye",
    "spokenText": "I need a dye.",
    "source": "beginner:part1.segments[5].mcqBeats[0].choices[1]"
  },
  "i need fish": {
    "path": "/audio/mcq/7f97fac696c02c663ea7.wav",
    "text": "I need fish",
    "spokenText": "I need fish.",
    "source": "beginner:part1.segments[8].mcqBeats[3].choices[2]"
  },
  "i need glass": {
    "path": "/audio/mcq/58833fa2f05968ab0f3e.wav",
    "text": "I need glass",
    "spokenText": "I need glass.",
    "source": "beginner:part1.segments[1].mcqBeats[1].choices[0]"
  },
  "i need more sand": {
    "path": "/audio/mcq/0a72eeaeab73aae1c268.wav",
    "text": "I need more sand",
    "spokenText": "I need more sand.",
    "source": "beginner:part1.segments[6].mcqBeats[3].choices[3]"
  },
  "i need sand": {
    "path": "/audio/mcq/8eac398c305599658c08.wav",
    "text": "I need sand",
    "spokenText": "I need sand.",
    "source": "beginner:part1.segments[1].mcqBeats[3].choices[0]"
  },
  "i need some sand": {
    "path": "/audio/mcq/7c84c4d801eb36f0dc87.wav",
    "text": "I need some sand",
    "spokenText": "I need some sand.",
    "source": "beginner:part1.segments[9].items[1].choices[1]"
  },
  "i need to make glass": {
    "path": "/audio/mcq/96896871660684af4858.wav",
    "text": "I need to make glass",
    "spokenText": "I need to make glass.",
    "source": "beginner:part1.segments[3].mcqBeats[0].choices[0]"
  },
  "i need water": {
    "path": "/audio/mcq/76604e867627bbed8cfa.wav",
    "text": "I need water",
    "spokenText": "I need water.",
    "source": "beginner:part1.segments[1].mcqBeats[1].choices[3]"
  },
  "i put glass here": {
    "path": "/audio/mcq/8bc60ddc781e0363e45c.wav",
    "text": "I put glass here",
    "spokenText": "I put glass here.",
    "source": "beginner:part1.segments[3].mcqBeats[0].choices[3]"
  },
  "i put sand here": {
    "path": "/audio/mcq/be36d20c99a0dd333448.wav",
    "text": "I put sand here",
    "spokenText": "I put sand here.",
    "source": "beginner:part1.segments[2].mcqBeats[2].choices[3]"
  },
  "i put the sand on the bottom": {
    "path": "/audio/mcq/f60b6289ebd6d1b204f0.wav",
    "text": "I put the sand on the bottom",
    "spokenText": "I put the sand on the bottom.",
    "source": "beginner:part1.segments[8].mcqBeats[0].choices[0]"
  },
  "i'm building a tank": {
    "path": "/audio/mcq/c4e58516abc452a1f6d1.wav",
    "text": "I'm building a tank",
    "spokenText": "I'm building a tank.",
    "source": "beginner:part1.segments[6].mcqBeats[1].choices[0]"
  },
  "i'm done!": {
    "path": "/audio/mcq/259da51fced0e4c1e78e.wav",
    "text": "I'm done!",
    "spokenText": "I'm done!",
    "source": "beginner:part1.segments[6].mcqBeats[3].choices[2]"
  },
  "it looks good!": {
    "path": "/audio/mcq/a71d2b1a6c4b98ca4dd6.wav",
    "text": "It looks good!",
    "spokenText": "It looks good!",
    "source": "beginner:part1.segments[6].mcqBeats[1].choices[2]"
  },
  "left": {
    "path": "/audio/mcq/a5729f20dda47f644872.wav",
    "text": "left",
    "spokenText": "left",
    "source": "beginner:part1.segments[2].mcqBeats[1].choices[0]"
  },
  "mountains": {
    "path": "/audio/mcq/63ee022edb2f894fe6da.wav",
    "text": "mountains",
    "spokenText": "mountains",
    "source": "beginner:part1.segments[2].mcqBeats[0].choices[1]"
  },
  "my tank is ready!": {
    "path": "/audio/mcq/8421e35b7de0992ca3fa.wav",
    "text": "My tank is ready!",
    "spokenText": "My tank is ready!",
    "source": "beginner:part1.segments[6].mcqBeats[2].choices[3]"
  },
  "right": {
    "path": "/audio/mcq/ec0666cdb4a51a0c0c63.wav",
    "text": "right",
    "spokenText": "right",
    "source": "beginner:part1.segments[2].mcqBeats[1].choices[1]"
  },
  "river": {
    "path": "/audio/mcq/e80354fb305b443822cc.wav",
    "text": "river",
    "spokenText": "river",
    "source": "beginner:part1.segments[2].mcqBeats[0].choices[2]"
  },
  "sand": {
    "path": "/audio/mcq/b68f38a6775ab30931ea.wav",
    "text": "sand",
    "spokenText": "sand",
    "source": "beginner:part1.segments[1].mcqBeats[2].choices[0]"
  },
  "stone": {
    "path": "/audio/mcq/f57aedd8c59bfa49b321.wav",
    "text": "stone",
    "spokenText": "stone",
    "source": "beginner:part1.segments[1].mcqBeats[2].choices[3]"
  },
  "straight": {
    "path": "/audio/mcq/e77cc157fa68998de810.wav",
    "text": "straight",
    "spokenText": "straight",
    "source": "beginner:part1.segments[2].mcqBeats[1].choices[2]"
  },
  "water": {
    "path": "/audio/mcq/f61ff807742994a52b60.wav",
    "text": "water",
    "spokenText": "water",
    "source": "beginner:part1.segments[1].mcqBeats[0].choices[2]"
  },
  "wood": {
    "path": "/audio/mcq/930acf389f0289b43ab9.wav",
    "text": "wood",
    "spokenText": "wood",
    "source": "beginner:part1.segments[1].mcqBeats[0].choices[1]"
  },
  "やま / mountains": {
    "path": "/audio/mcq/63ee022edb2f894fe6da.wav",
    "text": "やま / mountains",
    "spokenText": "mountains",
    "source": "beginner:part1.segments[2].choices[1]"
  },
  "ビーチ / beach": {
    "path": "/audio/mcq/b9c7a11ae474b8ee209e.wav",
    "text": "ビーチ / beach",
    "spokenText": "beach",
    "source": "beginner:part1.segments[2].choices[0]"
  }
});
