/** Homework lesson: aquarium Part 2 (week-4 review of week-3 real tank). Never invent the child's tank. */

export const AQUARIUM_PART2 = {
  id: "part2",
  title: "あの日の水族館を思い出そう！",
  titleEn: "Remember your aquarium",
  weekNote: "Week 4 homework — after the week-3 in-person class.",
  stopRule:
    "Never invent tank color, decorations, fish, or count. Only use record_memory or the child's last turn. Forgetting is not failure.",
  badges: [
    {
      id: "fish_finder",
      label: "Fish Finder",
      desc: "魚探しの英語を使えた",
      afterSegment: "ch4",
    },
    {
      id: "aquarium_memory",
      label: "Aquarium Memory",
      desc: "自分の水族館について思い出せた",
      afterSegment: "ch8",
    },
    {
      id: "quick_answer_p2",
      label: "Quick Answer",
      desc: "突然の日常英会話に答えた",
      afterSegment: "daily2",
    },
    {
      id: "aquarium_speaker",
      label: "Aquarium Speaker",
      desc: "水族館について複数の英語を使えた",
      minPhrases: 6,
    },
    {
      id: "aquarium_master",
      label: "Aquarium Master",
      desc: "Part 1 と Part 2 をやりきった",
      requiresPart1Complete: true,
      afterSegment: "ending2",
    },
  ],
  memories: [
    "tankColor",
    "decorations",
    "fishColor",
    "fishCount",
    "favoriteFish",
    "favoritePart",
  ],
  segments: [
    {
      id: "ch0",
      type: "warmup",
      title: "まずは今日のおしゃべり",
      titleEn: "Chat first",
      goal: "いきなり復習を始めない。",
      sampleQuestions: [
        "How are you today?",
        "What time is it?",
        "What did you eat today?",
        "What's your favorite food?",
        "What's your favorite summer food?",
        "Do you like the ocean or the mountains?",
        "What's your favorite animal?",
        "What did you do today?",
      ],
      completeWithoutEnglish: true,
      coach:
        "Natural chat first. Stay on their topic. Do not stack How are you with another question. After a few real exchanges, a SEPARATE turn: Remember the Minecraft aquarium class? Shall we remember YOUR tank? JP: このまえの まいんくらふとで つくった すいそう、おもいだそうか？ After yes/ok: call complete_segment(ch0) before recall questions.",
    },
    {
      id: "ch1",
      type: "recall",
      title: "水族館のこと覚えてる？",
      titleEn: "Do you remember?",
      goal: "Yes/No、日本語OK。テストにしない。",
      completeWithoutEnglish: true,
      coach:
        "Easy questions: Did you make an aquarium? Was it fun? Do you remember your tank? Japanese or yes/no is OK. Do not test. Wake the memory.",
    },
    {
      id: "ch2",
      type: "scaffold",
      title: "何色の水槽だった？",
      titleEn: "What color glass?",
      goal: "I chose ___ glass.",
      memoryKey: "tankColor",
      ask: "What color did you choose?",
      targets: [
        {
          id: "chose_glass",
          phrase: "I chose ___ glass.",
          patterns: ["i chose", "i choose", "glass"],
        },
        { id: "like_color", phrase: "I like blue.", patterns: ["i like", "favorite color"] },
      ],
      coach:
        "Ask What color did you choose? Use THEIR answer. Never guess blue. If they forget: blue? red? green? Then say I chose X glass together. You may ask Do you like that color?",
    },
    {
      id: "ch3",
      type: "scaffold",
      title: "水槽に何を飾った？",
      titleEn: "What did you put in?",
      goal: "coral / kelp / sand",
      memoryKey: "decorations",
      ask: "水槽の中には何を置いた？",
      targets: [
        { id: "put_coral", phrase: "I put coral here.", patterns: ["put coral", "coral here"] },
        { id: "put_kelp", phrase: "I put kelp here.", patterns: ["put kelp", "kelp"] },
        { id: "put_sand", phrase: "I put sand here.", patterns: ["put sand"] },
        { id: "choose_one", phrase: "I choose this one.", patterns: ["i choose this", "i like this coral"] },
        { id: "looks_cool", phrase: "It looks cool!", patterns: ["looks cool"] },
      ],
      coach:
        "Ask what they put in. If they forget, offer coral / kelp / sand. Never invent. Then I put X here. Which one did you like? Did it look cool?",
    },
    {
      id: "quiz1",
      type: "quiz",
      title: "覚えてるかな？",
      titleEn: "Quiz 1",
      goal: "3〜5問。選んだら声に出す。",
      items: [
        {
          promptJa: "サンゴをここに置いた、はどっち？",
          answer: "I put coral here.",
          patterns: ["put coral"],
          choices: ["I found coral.", "I put coral here."],
        },
        {
          promptJa: "この色のガラスを選んだ",
          answer: "I chose ___ glass.",
          patterns: ["i chose", "glass"],
          choices: ["I chose this glass.", "I caught this glass."],
        },
        {
          promptJa: "かっこいい！",
          answer: "It looks cool!",
          patterns: ["looks cool"],
          choices: ["It looks cool!", "I need cool!"],
        },
      ],
      coach:
        "3–5 items from phrases so far. Beginner: choices then SAY it. Intermediate: no choices first. Don't over-explain grammar. Don't make them repeat the wrong sentence.",
    },
    {
      id: "ch4",
      type: "scaffold",
      title: "魚を探した時を思い出そう",
      titleEn: "Finding fish",
      goal: "魚探しのフレーズ。色を覚えていなくても失敗にしない。",
      memoryKey: "fishColor",
      targets: [
        { id: "go_ocean", phrase: "Let's go to the ocean!", patterns: ["go to the ocean", "lets go"] },
        { id: "found_fish", phrase: "I found a fish!", patterns: ["i found a fish", "found a fish"] },
        { id: "found_color", phrase: "I found a blue fish!", patterns: ["found a", "fish"] },
        { id: "want_fish", phrase: "I want this fish.", patterns: ["i want this fish", "want this fish"] },
        { id: "choose_fish", phrase: "I choose this fish.", patterns: ["i choose this fish", "i chose this fish"] },
        { id: "caught", phrase: "I caught a fish!", patterns: ["i caught a fish", "caught a fish"] },
        { id: "have_fish", phrase: "I have a fish!", patterns: ["i have a fish", "have a fish"] },
      ],
      coach:
        "Remember looking for fish. Ask Did you find a fish? What fish / color? Did you catch one? Do not demand the exact real color if they forgot. Use I found a fish / I caught a fish / I want this fish etc.",
    },
    {
      id: "ch5",
      type: "scaffold",
      title: "魚は何匹いた？",
      titleEn: "How many fish?",
      goal: "How many ～? と数字。正確な記憶より練習。",
      memoryKey: "fishCount",
      ask: "How many fish are in your tank?",
      targets: [
        {
          id: "there_are",
          phrase: "There are ___ fish.",
          patterns: ["there are", "there is", "fish"],
        },
      ],
      coach:
        "How many fish are in your tank? If they remember, use that number: There are three fish. If not: 1? 3? 5? Priority is answering How many with a number, not a memory test.",
    },
    {
      id: "daily2",
      type: "daily_english",
      title: "突然英会話！",
      titleEn: "Daily English",
      goal: "水族館と無関係に2〜4問。",
      sampleQuestions: [
        "What time is it?",
        "What's your favorite summer food?",
        "Are you hungry?",
        "What color do you like?",
        "Do you like the ocean or the mountains?",
        "What's your favorite animal?",
        "What did you do today?",
        "What are you going to do after this?",
      ],
      completeWithoutEnglish: true,
      coach:
        "2–4 off-topic questions. One follow-up max. Then return to the aquarium memory.",
    },
    {
      id: "ch6",
      type: "scaffold",
      title: "魚を水槽に入れた時を思い出そう",
      titleEn: "Put the fish in",
      goal: "I put the fish in the tank.",
      targets: [
        {
          id: "put_in",
          phrase: "I put the fish in the tank.",
          patterns: ["put the fish in", "in the tank", "put it in"],
        },
        { id: "look", phrase: "Look! There's a fish!", patterns: ["there's a fish", "there is a fish", "look"] },
      ],
      coach:
        "What did you do with the fish you caught? If they say they put it in the tank, elicit I put the fish in the tank / I put it in here. Then Look! There's a fish!",
    },
    {
      id: "ch7",
      type: "scaffold",
      title: "一番好きだったところは？",
      titleEn: "Favorite part",
      goal: "正解のない会話。体験を短い英語に。",
      memoryKey: "favoritePart",
      completeWithoutEnglish: false,
      targets: [
        { id: "like_fish", phrase: "I like this fish.", patterns: ["i like", "this fish", "the blue fish"] },
        { id: "yes_i_do", phrase: "Yes, I do!", patterns: ["yes i do", "i like my aquarium"] },
      ],
      coach:
        "No single correct answer. Which fish did you like? Favorite part? Do you like your aquarium? Beginners may answer in Japanese; you turn it into a short English line and they repeat. Record favoritePart / favoriteFish.",
    },
    {
      id: "quiz2",
      type: "quiz",
      title: "どっちが正しい？",
      titleEn: "Quiz 2",
      goal: "2択のあと正しい英語を言う。",
      items: [
        {
          promptJa: "魚を捕まえた！はどっち？",
          answer: "I caught a fish!",
          patterns: ["caught a fish"],
          choices: ["I caught a fish!", "I made a fish!"],
        },
        {
          promptJa: "魚が3匹いる！はどっち？",
          answer: "There are three fish.",
          patterns: ["there are"],
          choices: ["There is three fish.", "There are three fish."],
        },
        {
          promptJa: "この魚が好き！はどっち？",
          answer: "I like this fish.",
          patterns: ["i like this fish"],
          choices: ["I like this fish.", "I need this fish."],
        },
        {
          promptJa: "魚を水槽に入れた！はどっち？",
          answer: "I put the fish in the tank.",
          patterns: ["put the fish in"],
          choices: ["I put the fish in the tank.", "I found the fish in the tank."],
        },
        {
          promptJa: "この魚を選んだ！はどっち？",
          answer: "I chose this fish.",
          patterns: ["i chose this fish"],
          choices: ["I chose this fish.", "I caught this fish."],
        },
      ],
      coach:
        "Beginner 3–5 items with choices then speak. Intermediate: elicit first, choices if stuck. Don't explain hard grammar. Don't make them read the wrong sentence. Don't stop the lesson for score.",
    },
    {
      id: "ch8",
      type: "recap",
      title: "水族館メモリーを完成させよう",
      titleEn: "Recap memories",
      goal: "1つずつ。全部説明させない。",
      coach:
        "ONE question at a time using stored memories. 1 What color did you choose? 2 What did you put in? 3 What fish? 4 How many? 5 Which fish did you like? 6 Do you like your aquarium? Never dump describe everything. Use their words.",
      completeWithoutEnglish: false,
      targets: [
        { id: "recap_color", phrase: "I chose ___ glass.", patterns: ["i chose", "glass"] },
        { id: "recap_put", phrase: "I put coral here.", patterns: ["i put"] },
        { id: "recap_fish", phrase: "I chose ___.", patterns: ["i chose", "i like"] },
        { id: "recap_count", phrase: "There are ___ fish.", patterns: ["there are"] },
        { id: "recap_like", phrase: "I like ___.", patterns: ["i like"] },
        { id: "recap_yes", phrase: "Yes, I do!", patterns: ["yes i do", "i like my aquarium"] },
      ],
    },
    {
      id: "final2",
      type: "final_challenge",
      input: "speak_or_click",
      title: "水族館の思い出チャレンジ！",
      titleEn: "Final challenge",
      goal: "8〜12問をランダムに。",
      items: [
        { promptJa: "魚を見つけた！", answer: "I found a fish!", patterns: ["found a fish"] },
        { promptJa: "この魚がほしい！", answer: "I want this fish.", patterns: ["want this fish"] },
        { promptJa: "魚を捕まえた！", answer: "I caught a fish!", patterns: ["caught a fish"] },
        { promptJa: "サンゴをここに置いた！", answer: "I put coral here.", patterns: ["put coral"] },
        { promptJa: "魚を水槽に入れた！", answer: "I put the fish in the tank.", patterns: ["put the fish in"] },
        { promptJa: "魚が3匹いる！", answer: "There are three fish.", patterns: ["there are"] },
        { promptJa: "この魚が好き！", answer: "I like this fish.", patterns: ["i like this fish"] },
        { promptJa: "これが私の水族館！", answer: "This is my aquarium.", patterns: ["this is my aquarium"] },
        { promptJa: "この魚を選んだ", answer: "I chose this fish.", patterns: ["i chose this fish"] },
        { promptJa: "海に行こう", answer: "Let's go to the ocean!", patterns: ["go to the ocean"] },
      ],
      coach:
        "Shuffle 8–12. Beginner: hints/choices. Intermediate: unaided first. Optional on-screen 3-choice if speaking is too hard.",
    },
    {
      id: "mix1",
      type: "mix_review",
      title: "Part 1 も少し復習",
      titleEn: "Part 1 mix-in",
      goal: "2〜4問だけ Part 1 フレーズ。",
      items: [
        { promptJa: "ガラスが必要", answer: "I need glass.", patterns: ["need glass"] },
        { promptJa: "砂を見つけた", answer: "I found some sand!", patterns: ["found some sand", "found sand"] },
        { promptJa: "ガラスを作った", answer: "I made glass!", patterns: ["made glass"] },
        { promptJa: "もっと砂が必要", answer: "I need more sand.", patterns: ["need more sand"] },
        { promptJa: "水槽の準備できた", answer: "My tank is ready!", patterns: ["tank is ready"] },
      ],
      coach: "Only 2–4 Part 1 phrases. Celebrate if they remember from weeks ago.",
    },
    {
      id: "ending2",
      type: "ending",
      title: "おしまい",
      titleEn: "Ending",
      completeWithoutEnglish: true,
      coach:
        "Praise remembering THEIR aquarium and the English. Mention badges they earned (including Aquarium Master if Part 1 was already done). Encourage using This is my aquarium / There are ___ fish / I like this fish next time they play Minecraft — optional, not required.",
    },
  ],
};
