#!/usr/bin/env python3
"""Generate and validate hosted Gemini TTS audio for fixed Mini Quiz 1 Q1."""

from __future__ import annotations

import argparse
from array import array
import base64
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import time
import wave

ROOT = Path(__file__).resolve().parents[1]
EXTRACTOR = ROOT / "scripts" / "extract-quiz1-audio.mjs"
OUTPUT_DIR = ROOT / "audio" / "quiz1"
MANIFEST_PATH = OUTPUT_DIR / "manifest.js"

MODEL = "gemini-3.1-flash-tts-preview"
VOICE = "Kore"
PROMPT_VERSION = "warm-japanese-exact-v1"
SAMPLE_RATE = 24_000
CHANNELS = 1
SAMPLE_WIDTH = 2


def load_scripts() -> list[dict]:
    result = subprocess.run(
        ["node", str(EXTRACTOR)],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def audio_id(item: dict) -> str:
    identity = json.dumps(
        {
            "model": MODEL,
            "voice": VOICE,
            "promptVersion": PROMPT_VERSION,
            "text": item["text"],
        },
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(identity.encode("utf-8")).hexdigest()[:20]


def valid_wav(path: Path) -> bool:
    try:
        with wave.open(str(path), "rb") as audio:
            format_ok = (
                audio.getnchannels() == CHANNELS
                and audio.getsampwidth() == SAMPLE_WIDTH
                and audio.getframerate() == SAMPLE_RATE
                and audio.getnframes() > SAMPLE_RATE // 2
            )
            if not format_ok:
                return False
            samples = array("h")
            samples.frombytes(audio.readframes(audio.getnframes()))
            return bool(samples) and max(abs(sample) for sample in samples) > 256
    except (EOFError, OSError, wave.Error):
        return False


def synthesis_prompt(text: str) -> str:
    return (
        "Read the following Japanese lesson script exactly as written. "
        "Use a warm, friendly teacher voice for a young child and a natural, "
        "upbeat pace. Pronounce every mora clearly, including the cue inside "
        "the Japanese quotation marks. Do not add, remove, translate, repeat, "
        "or explain any words.\n"
        f"Lesson script: {text}"
    )


def generate_one(client, item: dict) -> dict:
    filename = f"{audio_id(item)}.wav"
    output_path = OUTPUT_DIR / filename
    if valid_wav(output_path):
        return {**item, "filename": filename, "cached": True}

    last_error = None
    for attempt in range(3):
        try:
            response = client.interactions.create(
                model=MODEL,
                input=synthesis_prompt(item["text"]),
                response_format={"type": "audio"},
                generation_config={"speech_config": [{"voice": VOICE}]},
            )
            audio = response.output_audio
            if not audio or not audio.data:
                raise RuntimeError("Gemini returned no audio data")
            if int(audio.sample_rate or SAMPLE_RATE) != SAMPLE_RATE:
                raise RuntimeError(f"Unexpected sample rate: {audio.sample_rate}")
            pcm = base64.b64decode(audio.data)
            temp_path = output_path.with_suffix(".wav.tmp")
            with wave.open(str(temp_path), "wb") as wav:
                wav.setnchannels(CHANNELS)
                wav.setsampwidth(SAMPLE_WIDTH)
                wav.setframerate(SAMPLE_RATE)
                wav.writeframes(pcm)
            temp_path.replace(output_path)
            if not valid_wav(output_path):
                raise RuntimeError("Generated WAV failed validation")
            return {**item, "filename": filename, "cached": False}
        except Exception as error:  # SDK exceptions vary by API status.
            last_error = error
            if attempt < 2:
                time.sleep(2**attempt)
    raise RuntimeError(f"Failed to generate {item['key']!r}: {last_error}")


def manifest_source(results: list[dict]) -> str:
    entries = {
        item["key"]: {
            "path": f"/audio/quiz1/{item['filename']}",
            "text": item["text"],
            "source": item["source"],
        }
        for item in sorted(results, key=lambda value: value["key"])
    }
    metadata = {
        "model": MODEL,
        "voice": VOICE,
        "promptVersion": PROMPT_VERSION,
        "sampleRate": SAMPLE_RATE,
        "count": len(entries),
    }
    return (
        "// Generated by scripts/generate-quiz1-audio.py. Do not edit manually.\n"
        f"export const QUIZ1_AUDIO_METADATA = Object.freeze({json.dumps(metadata, ensure_ascii=False, indent=2)});\n\n"
        f"export const QUIZ1_AUDIO_MANIFEST = Object.freeze({json.dumps(entries, ensure_ascii=False, indent=2)});\n"
    )


def validate(items: list[dict]) -> None:
    if not MANIFEST_PATH.exists():
        raise RuntimeError(f"Missing manifest: {MANIFEST_PATH}")
    result = subprocess.run(
        [
            "node",
            "--input-type=module",
            "-e",
            (
                f"import {{ QUIZ1_AUDIO_MANIFEST }} from {json.dumps(MANIFEST_PATH.as_uri())};"
                "process.stdout.write(JSON.stringify(QUIZ1_AUDIO_MANIFEST));"
            ),
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    manifest = json.loads(result.stdout)
    expected = {
        item["key"]: f"/audio/quiz1/{audio_id(item)}.wav" for item in items
    }
    missing = [key for key in expected if key not in manifest]
    unexpected = [key for key in manifest if key not in expected]
    mismatched = [
        key
        for key, path in expected.items()
        if key in manifest
        and (
            manifest[key].get("path") != path
            or manifest[key].get("text")
            != next(item["text"] for item in items if item["key"] == key)
        )
    ]
    invalid = [
        f"{audio_id(item)}.wav"
        for item in items
        if not valid_wav(OUTPUT_DIR / f"{audio_id(item)}.wav")
    ]
    if missing or unexpected or mismatched or invalid:
        raise RuntimeError(
            f"Audio validation failed: {len(missing)} missing manifest entries, "
            f"{len(unexpected)} unexpected entries, {len(mismatched)} mismatched entries, "
            f"{len(invalid)} missing/invalid WAV files"
        )
    print(f"Validated {len(items)} quiz1 audio entries.")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--validate", action="store_true")
    args = parser.parse_args()
    items = load_scripts()
    if args.validate:
        validate(items)
        return

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    needs_generation = any(
        not valid_wav(OUTPUT_DIR / f"{audio_id(item)}.wav") for item in items
    )
    client = None
    if needs_generation:
        api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
        if not api_key:
            raise SystemExit("Set GEMINI_API_KEY before generating new audio.")
        from google import genai

        client = genai.Client(api_key=api_key)
    results = []
    for index, item in enumerate(items, 1):
        result = generate_one(client, item)
        results.append(result)
        state = "cached" if result["cached"] else "generated"
        print(f"[{index}/{len(items)}] {state}: {result['key']}")
    MANIFEST_PATH.write_text(manifest_source(results), encoding="utf-8")
    validate(items)


if __name__ == "__main__":
    try:
        main()
    except (RuntimeError, subprocess.CalledProcessError) as error:
        print(error, file=sys.stderr)
        raise SystemExit(1)
