/** Beginner Lesson 1 — Minecraft survival quest chain (one quest per voice call). */
export const LESSON_1_TITLE = "レッスン1：マイクラサバイバル";

export const LESSON_1_QUESTS = [
  {
    id: 1,
    title: "クエスト1",
    titleEn: "Find a tree and chop it for wood",
    goal: "木を見つけて、切って木材を集めよう",
    hint: "例：「I found a tree!」→「I got wood!」",
    openingPlay:
      "まずは木を探そう！サバイバル、木が大事だよ。見つかったら「I found a tree!」って言ってみよう！",
    steps: [
      {
        id: "found_tree",
        label: "木を見つけた",
        patterns: [
          "I found a tree",
          "found a tree",
          "find a tree",
          "found tree",
          "find tree",
          "see a tree",
          "see tree",
          "there's a tree",
          "there is a tree",
          "i see a tree",
          "chopping the tree",
          "chopping tree",
          "chop the tree",
          "chop tree",
          "i am chopping the tree",
          "i'm chopping the tree",
        ],
        coachNote:
          "「I found a tree」= 木を見つけたよ。found（ファウンド）= 見つけた、tree（ツリー）= 木",
      },
      {
        id: "got_wood",
        label: "木材を手に入れた",
        patterns: [
          "I got wood",
          "got wood",
          "get wood",
          "got the wood",
          "get the wood",
          "got some wood",
          "have wood",
          "chopped wood",
          "chop wood",
          "chop tree",
          "chop the tree",
          "chopped the tree",
          "cut the tree",
          "collected wood",
          "i have wood",
          "i got the wood",
        ],
        coachNote:
          "「I got wood」= 木材を手に入れた。got（ガット）= 手に入れた、wood（ウッド）= 木の材料・木材",
      },
    ],
  },
  {
    id: 2,
    title: "クエスト2",
    titleEn: "Craft and place a crafting table",
    goal: "作業台を作って、置こう",
    hint: "例：「I made a crafting table!」→「I put it here!」",
    openingPlay:
      "木材があるね！次は作業台をクラフトして、好きな場所に置いてみよう！作れたら「I made a crafting table!」って言ってみよう！",
    steps: [
      {
        id: "made_table",
        label: "作業台を作った",
        patterns: [
          "I made a crafting table",
          "made a crafting table",
          "make a crafting table",
          "made crafting table",
          "make crafting table",
          "made a craft table",
          "make a craft table",
          "made a table",
          "make a table",
          "made table",
          "make table",
          "craft table",
          "crafting table",
          "crafted a crafting table",
          "built a crafting table",
          "created a crafting table",
          "i made a table",
          "i crafted a table",
        ],
        coachNote:
          "「I made a crafting table」= 作業台を作った。made（メイド）= 作った、crafting table（クラフティング・テーブル）= 作業台",
      },
      {
        id: "placed_table",
        label: "作業台を置いた",
        patterns: [
          "I put it here",
          "put it here",
          "put here",
          "i put here",
          "placed it here",
          "place it here",
          "put it down",
          "put down",
          "placed the table",
          "place the table",
          "put the table",
          "placed the crafting table",
          "put it there",
          "place here",
        ],
        coachNote:
          "「I put it here」= ここに置いた。put（プット）= 置く、here（ヒア）= ここ",
      },
    ],
  },
  {
    id: 3,
    title: "クエスト3",
    titleEn: "Make a wooden pickaxe",
    goal: "木のツルハシを作ろう",
    hint: "例：「I made a pickaxe!」→「I'm ready!」",
    openingPlay:
      "作業台の前で木のツルハシを作ってみよう！サバイバルに超大事なアイテムだよ。できたら「I made a pickaxe!」って言ってみよう！",
    steps: [
      {
        id: "made_pickaxe",
        label: "ツルハシを作った",
        patterns: [
          "I made a pickaxe",
          "made a pickaxe",
          "make a pickaxe",
          "made pickaxe",
          "make pickaxe",
          "made a wooden pickaxe",
          "make a wooden pickaxe",
          "crafted a pickaxe",
          "built a pickaxe",
          "i have a pickaxe",
        ],
        coachNote:
          "「I made a pickaxe」= ツルハシを作った。made（メイド）= 作った、pickaxe（ピカックス）= ツルハシ",
      },
      {
        id: "ready",
        label: "準備OK",
        patterns: [
          "I'm ready",
          "im ready",
          "i am ready",
          "ready to go",
          "ready now",
          "ready",
        ],
        coachNote:
          "「I'm ready」= 準備できた。ready（レディ）= 準備OK・用意できた",
      },
    ],
  },
  {
    id: 4,
    title: "クエスト4",
    titleEn: "Mine 5 stones (cobblestone)",
    goal: "石（丸石）を5個掘ろう",
    hint: "例：「I found stones!」→「I got stones!」",
    openingPlay:
      "ツルハシを持って石を探そう！掘って集めてみて。見つけたら「I found stones!」って言ってみよう！",
    steps: [
      {
        id: "found_stones",
        label: "石を見つけた",
        patterns: [
          "I found stones",
          "found stones",
          "find stones",
          "found stone",
          "find stone",
          "found the stones",
          "found the stone",
          "see stones",
          "see stone",
          "found cobblestone",
          "find cobblestone",
          "mine cobblestone",
          "see cobblestone",
        ],
        coachNote:
          "「I found stones」= 石を見つけた。found（ファウンド）= 見つけた、stones（ストーンズ）= 石",
      },
      {
        id: "got_stones",
        label: "石を集めた",
        patterns: [
          "I got stones",
          "got stones",
          "get stones",
          "got stone",
          "get stone",
          "collected stones",
          "collected stone",
          "mined stone",
          "mined stones",
          "mine stone",
          "have stones",
          "have five stones",
          "got five stones",
          "got 5 stones",
        ],
        coachNote:
          "「I got stones」= 石を集めた。got（ガット）= 手に入れた・集めた、stones（ストーンズ）= 石",
      },
    ],
  },
  {
    id: 5,
    title: "クエスト5",
    titleEn: "Find food to survive",
    goal: "食べ物を見つけてサバイバルしよう",
    hint: "例：「I found food!」（お肉・フルーツなど）→「I need food!」",
    openingPlay:
      "お腹空いてきたね！ワールドで食べ物を探してみよう。羊や牛、木の実…見つけたら「I found food!」って言ってみよう！",
    steps: [
      {
        id: "found_food",
        label: "食べ物を見つけた",
        patterns: [
          "I found food",
          "found food",
          "find food",
          "found some food",
          "got food",
          "get food",
          "found beef",
          "found meat",
          "found apple",
          "found fruit",
          "found bread",
          "found lamb",
          "found a sheep",
          "found a cow",
        ],
        coachNote:
          "「I found food」= 食べ物を見つけた。found（ファウンド）= 見つけた、food（フード）= 食べ物",
      },
      {
        id: "need_food",
        label: "お腹が空いた",
        patterns: [
          "I need food",
          "need food",
          "i'm hungry",
          "im hungry",
          "i am hungry",
          "hungry",
          "need to eat",
          "want food",
          "i want food",
          "want to eat",
        ],
        coachNote:
          "「I need food」= 食べ物が必要・お腹が空いた。need（ニード）= 必要、food（フード）= 食べ物",
      },
    ],
  },
  {
    id: 6,
    title: "クエスト6",
    titleEn: "Make a stone tool",
    goal: "石の道具を作ろう（剣・シャベル・ツルハシなんでもOK）",
    hint: "例：「I made a stone tool!」→「It's strong!」",
    openingPlay:
      "石が集まったね！次はその石で好きな道具を作ってみよう。剣でもシャベルでもツルハシでもOK！できたら「I made a stone tool!」って言ってみよう！",
    steps: [
      {
        id: "made_stone_tool",
        label: "石の道具を作った",
        patterns: [
          "I made a stone tool",
          "made a stone tool",
          "made stone tools",
          "made the stone tool",
          "crafted a stone tool",
          "built a stone tool",
          "I made a stone pickaxe",
          "made a stone pickaxe",
          "I made a pickaxe",
          "made a pickaxe",
          "I made a stone axe",
          "made a stone shovel",
          "I made a stone sword",
        ],
        coachNote:
          "「I made a stone tool」= 石の道具を作った。made（メイド）= 作った、stone（ストーン）= 石、tool（トゥール）= 道具。剣でもシャベルでもツルハシでもOK！",
        japaneseHints: ["石の剣", "剣", "シャベル", "ツルハシ", "道具", "作っ", "作れた", "できた", "ソード"],
      },
      {
        id: "its_strong",
        label: "強いぞ！",
        patterns: [
          "It's strong",
          "it is strong",
          "its strong",
          "so strong",
          "very strong",
          "strong",
        ],
        coachNote:
          "「It's strong!」= これ強い！strong（ストロング）= 強い。作った道具を自慢しちゃおう！",
        japaneseHints: ["強い", "つよい", "ストロング", "最強"],
      },
    ],
  },
  {
    id: 7,
    title: "クエスト7",
    titleEn: "Make a furnace",
    goal: "かまどを作って、置こう",
    hint: "例：「I made a furnace!」→「I put it here!」",
    // Quiz-first: Learny asks the phrase as a quiz before teaching it.
    // Answering with no hints earns the hidden badge.
    quizFirst: true,
    hiddenBadge: { id: "hidden_furnace" },
    openingPlay:
      "次はかまど（furnace）を作ってみよう！その前にクイズ！かまどが作れたとき、英語でなんて言うと思う？知ってたら言ってみて！",
    steps: [
      {
        id: "made_furnace",
        label: "かまどを作った",
        patterns: [
          "I made a furnace",
          "made a furnace",
          "made furnace",
          "make a furnace",
          "crafted a furnace",
          "built a furnace",
          "created a furnace",
          "i have a furnace",
        ],
        coachNote:
          "「I made a furnace」= かまどを作った。made（メイド）= 作った、furnace（ファーネス）= かまど",
        japaneseHints: ["かまど", "カマド", "ファーネス", "作っ", "作れた", "できた"],
      },
      {
        id: "placed_furnace",
        label: "かまどを置いた",
        patterns: [
          "I put it here",
          "put it here",
          "put here",
          "i put here",
          "placed it here",
          "place it here",
          "put it down",
          "put down",
          "placed the furnace",
          "put the furnace",
          "put it there",
          "place here",
        ],
        coachNote:
          "「I put it here」= ここに置いた。put（プット）= 置く、here（ヒア）= ここ",
        japaneseHints: ["置い", "置き", "置く", "ここに"],
      },
    ],
  },
  {
    id: 8,
    title: "クエスト8",
    titleEn: "Find iron",
    goal: "てつ（アイアン）を見つけて掘ろう",
    hint: "例：「I found iron!」→「I got iron!」",
    sideChallenge: {
      id: "hidden_iron",
      label: "シークレットチャレンジ",
      desc: "てつを2個以上あつめる（例:「I got two irons!」）か、てつの道具を作る（例:「I made an iron sword!」）",
    },
    openingPlay:
      "かまどの次はてつ探し！てつは石より深いところにあるよ。ツルハシを持って探してみよう。見つけたら「I found iron!」って言ってみよう！",
    steps: [
      {
        id: "found_iron",
        label: "てつを見つけた",
        patterns: [
          "I found iron",
          "found iron",
          "found irons",
          "find iron",
          "found an iron",
          "found iron ore",
          "i see iron",
          "see iron",
          "there is iron",
        ],
        coachNote:
          "「I found iron」= てつを見つけた。found（ファウンド）= 見つけた、iron（アイアン）= てつ",
        japaneseHints: ["鉄", "アイアン", "見つけ", "あった", "発見"],
      },
      {
        id: "got_iron",
        label: "てつを手に入れた",
        patterns: [
          "I got iron",
          "got iron",
          "got irons",
          "get iron",
          "got the iron",
          "have iron",
          "mined iron",
          "mine iron",
          "dug iron",
          "collected iron",
          "got iron ore",
        ],
        coachNote:
          "「I got iron」= てつを手に入れた。got（ガット）= 手に入れた、iron（アイアン）= てつ",
        japaneseHints: ["鉄", "掘っ", "取っ", "手に入", "ゲット", "集め"],
      },
    ],
  },
  {
    id: 9,
    title: "クエスト9",
    titleEn: "Find a cave and decide what to do",
    goal: "どうくつを見つけて、次にやることを自分で決めよう",
    hint: "例：「I found a cave!」→「I want to explore!」",
    openingPlay:
      "探検の時間だ！どうくつ（cave）を探してみよう。見つけたら「I found a cave!」って言ってね。そのあと、次に何をしたいか英語で教えて！",
    steps: [
      {
        id: "found_cave",
        label: "どうくつを見つけた",
        patterns: [
          "I found a cave",
          "found a cave",
          "found cave",
          "find a cave",
          "i see a cave",
          "see a cave",
          "there is a cave",
          "there's a cave",
        ],
        coachNote:
          "「I found a cave」= どうくつを見つけた。found（ファウンド）= 見つけた、cave（ケイブ）= どうくつ",
        japaneseHints: ["洞窟", "どうくつ", "ケイブ", "穴", "見つけ", "あった"],
      },
      {
        id: "decide_action",
        label: "やることを決めた",
        display: "I want to 〇〇!",
        spokenPhrase:
          'I want to explore! (an example — the child says whatever THEY want to do: "I want to fight!", "I will build a house!"... anything counts. In Japanese, say the blank as「まるまる」— NEVER pronounce the symbol 〇〇)',
        patterns: [
          "I want to ...",
          "i want to",
          "i will",
          "i'll",
          "i'm going to",
          "i am going to",
          "let's go",
          "lets go",
          "i decided to",
          "i choose",
          "we should",
        ],
        coachNote:
          "「I want to explore!」= 探検したい！want to（ウォント・トゥ）= 〜したい。どうくつでやりたいことを自分で決めて英語で言ってみよう。なんでもOK！",
        japaneseHints: ["したい", "やりたい", "行きたい", "行く", "探検", "決めた"],
      },
    ],
  },
  {
    id: 10,
    title: "クエスト10",
    titleEn: "Review: say what you did!",
    goal: "今日の冒険を英語でふりかえろう",
    hint: "例：「I found iron!」「I made a furnace!」「I want to build a house!」「I did it!」",
    openingPlay:
      "ラストミッション！今日の冒険をふりかえるよ。今日「見つけたもの」を英語で1つ言ってもらおう。具体例で教える — 「I found iron!」「I found a cave!」みたいに。日本語で穴あきを言うときは「I found まるまる」と言う（「〇〇」という記号は絶対に読み上げない）",
    steps: [
      {
        id: "review_found",
        label: "見つけたものを言う",
        display: "I found 〇〇!",
        spokenPhrase:
          'I found iron! (an example — the child names anything THEY found today: tree, stone, iron, cave... In Japanese, say the blank as「まるまる」— NEVER pronounce the symbol 〇〇)',
        patterns: ["I found ...", "i found", "found"],
        coachNote:
          "「I found ◯◯」= ◯◯を見つけた。今日見つけたものを思い出そう（tree, stone, iron, cave...）",
        japaneseHints: ["見つけ", "あった", "発見"],
      },
      {
        id: "review_made",
        label: "作ったものを言う",
        display: "I made 〇〇!",
        spokenPhrase:
          'I made a furnace! (an example — the child names anything THEY made today: table, pickaxe, furnace... In Japanese, say the blank as「まるまる」— NEVER pronounce the symbol 〇〇)',
        patterns: ["I made ...", "i made", "made"],
        coachNote:
          "「I made ◯◯」= ◯◯を作った。今日作ったものを思い出そう（table, pickaxe, furnace...）",
        japaneseHints: ["作っ", "作れた", "できた", "クラフト"],
      },
      {
        id: "review_want",
        label: "次にやりたいことを言う",
        display: "I want to 〇〇!",
        spokenPhrase:
          'I want to find diamonds! (an example — the child says whatever THEY want to do next. In Japanese, say the blank as「まるまる」— NEVER pronounce the symbol 〇〇)',
        patterns: ["I want to ...", "i want to", "want to"],
        coachNote:
          "「I want to ◯◯」= ◯◯したい。次の冒険でやりたいことを言ってみよう！",
        japaneseHints: ["したい", "やりたい", "つぎは", "今度"],
      },
      {
        id: "review_did",
        label: "「I did it!」でお祝い",
        patterns: ["I did it!", "i did it", "we did it", "did it"],
        coachNote:
          "「I did it!」= やったー！できた！ミッションクリアのおまじない",
        japaneseHints: ["できた", "やった", "クリア", "終わっ"],
      },
    ],
  },
];
